apiVersion: batch/v1
kind: Job
metadata:
  name: lb4b-nst-job-%DFM%
spec:
  parallelism: 1
  template:
    metadata:
      name: lb4b-nst-job-%DFM%
      labels:
        app: lb4b-nst-app
    spec:
      containers:
      - name: lb4b-nst-job-%DFM%
        image: gcr.io/prismatic-rock-334703/lb4b_nst_job:0.0.1
        resources: 
          requests: 
            nvidia.com/gpu: 1
          limits: 
            nvidia.com/gpu: 1
        args: [ --dfm=%DFM%,--bg=%BG%,--usrImg=%IMG% ]
      nodeSelector:
        gpu: tesla-T4 
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nst-app
            topologyKey: "kubernetes.io/hostname"
      tolerations:
      - key: cloud.google.com/gke-spot
        operator: Equal
        value: "true"
        effect: NoSchedule
      restartPolicy: OnFailure
