apiVersion: batch/v1
kind: Job
metadata:
  name: lb4b_nst_job
spec:
  parallelism: 1
  template:
    metadata:
      name: lb4b_nst_job
      labels:
        app: nst-app
    spec:
      nodeSelector:
        gpu: tesla-T4
      containers:
      - name: lb4b_nst_job
        image: gcr.io/prismatic-rock-334703/lb4b_nst_job:1.0.0
        args:
        - [ "--dfm","%DFM%","--bg","%BG%","--usrImg", "%IMG%" ]
        resources: 
            requests: 
              nvidia.com/gpu: 1
            limits: 
              nvidia.com/gpu: 1 
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nst-app
            topologyKey: "kubernetes.io/hostname"
      tolerations:
      - key: cloud.google.com/gke-spot
        operator: Equal
        value: "true"
        effect: NoSchedule
      restartPolicy: OnFailure
